### ISSUE TITLE
Write a pretty README.

### ISSUE THREAD

**Issue by ILoveChairs** [alisonalvezz/shell-communal_checker#1]
I created the README, but i don't have time to finish it. Can someone with artistic background finish it and make it pretty?

**Comment by alisonalvezz** [comment]
idk what you mean by finish it, but I made it prettier than it was and translated it

**Comment by ILoveChairs** [comment]
I meant the main readme, not really the makefile one. And i don't know what you mean by translating it, it was written in English and then rewritten on English. Although some meaning has been lost with the changes i'm not here to argue, it looks quite good.

**Comment by alisonalvezz** [comment]
No, the readme in the makefile was originally in spanish, that's why I said I translated it, I know that some meaning was lost but i think its bc it was in spanish. However, I can make the main readme prettier too! If you want to make some changes to the readme that I changed, feel free to do that.

**Comment by ILoveChairs** [comment]
Ye you're right i forgor.
